apiVersion: v1
kind: ConfigMap
metadata:
  name: read-ahead-rule
  namespace: kube-system

data:
  90-nfs-readahead.rules: |
    SUBSYSTEM=="bdi" 
    ACTION=="add" 
    PROGRAM="/usr/bin/awk -v bdi=$kernel 'BEGIN{ret=1} {if ($4 == bdi) {ret=0}} END{exit ret}' /proc/fs/nfsfs/volumes" 
    ATTR{read_ahead_kb}="16384"
